### ISSUE TITLE
v1.1 """tracking issue"""

### ISSUE THREAD

**Issue by portal-chan** [portal-chan/EndModLoader#1]
- [x] Prompt before deleting modded folders before playing a MOD.
- [x] A "description" tag in meta.xml, displays next to the name.
- [x] Report an error when it tries deleting an open file instead of crashing.
- [x] Warn before exiting the MOD loader if the user is currently in game.
